project:
  type: website
  output-dir: docs

website:
  title: "Brendan's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bkaradenes25/ds334block/tree/master
format:
  html:
    theme: slate
    css: styles.css



